config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  post '/paper_trail_versions/:id/revert', to: 'paper_trail_versions#revert', as: :revert_paper_trail_version

  resources :charts do
    collection do
      get :student_fees
    end
  end

  resources :graphql, only: [:index, :create]

  mount GraphiQL::Rails::Engine, at: "/graphiql", graphql_path: "/graphql"

  mount Client::Route => '/client'
  mount Partner::Route => '/agency'
end

app/models/student.rb
class Student < User

  has_many :lesson_schedules, class_name: LessonSchedule, foreign_key: :student_id

  has_many :courses, foreign_key: :student_id, dependent: :destroy
  has_many :course_teachers, through: :courses, source: :course_teachers
  has_many :teachers, -> { distinct }, through: :course_teachers, source: :teacher

  has_many :active_courses, -> { in_process }, class_name: Course, foreign_key: :student_id, dependent: :destroy
  has_many :active_course_teachers, -> { active  }, through: :courses, source: :course_teachers
  has_many :active_teachers, -> { distinct }, through: :active_course_teachers, source: :teacher

  has_one :latest_course, -> { order('id DESC') }, class_name: Course, foreign_key: :student_id

  has_many :homework_students, foreign_key: :student_id
  has_many :homeworks, through: :homework_students
end

app/controllers/client/v1/student.rb
module Client
  module V1
    class Student < Grape::API
      include Helper

      helpers do
        def repository
          StudentRepository.find(params[:id])
        end
      end

      resource :students do
        get ':id' do
          respond_with(repository)
        end

        get ':id/teachers' do
          render repository.student.active_teachers, each_serializer: TeacherSerializer
        end
      end
    end
  end
end

app/views/admin/dashboard/student/_form.haml
%form.formtastic{ url: dashboard_student_path, method: :get }
  %fieldset.inputs
    %legend
      %span Statistic in range
    %ol
      %li
        %label Student
        - selectors = [OpenStruct.new({ id: :all, nickname: 'All students' })] + Pundit.policy_scope(current_admin_user, Student.active).order(:nickname)
        = select_tag "student_id", options_from_collection_for_select(selectors, :id, :nickname, statistic.student_id)
      %li.time-zone
        %label Time Zone
        = select_tag "time_zone", options_for_select(ActiveSupport::TimeZone.all.map { |tz| [tz.to_s, tz.name] }, params[:time_zone] || 'Hanoi')
      %li.started-date
        %label Started Date
        %input.datepicker{ type: :text, name: 'started_date', value: "#{statistic.started_date}" }
      %li.ended-date
        %label Ended Date
        %input.datepicker{ type: :text, name: 'ended_date', value: "#{statistic.ended_date}" }
  %fieldset.actions
    %ol
      %li
        %input{ type: :submit, name: :commit, value: 'Submit' }
:javascript
  $(function() {
    checkDateSelectors();

    $('#student_id').on('change', function() {
      checkDateSelectors();
    })

    function checkDateSelectors() {
      if ($('#student_id').val() == 'all') {
        $('.started-date').removeClass('hide');
        $('.ended-date').removeClass('hide');
        $('.time-zone').removeClass('hide');
      } else {
        $('.started-date').addClass('hide');
        $('.ended-date').addClass('hide');
        $('.time-zone').addClass('hide');
      }
    }
  })

app/views/admin/dashboard/student/_statistic.haml
%br
#statistic
  .header Statistic
  .body
    .row
      .column-20
        .label Student Name
      .column-80
        %span= student.full_name
    .row
      .column-20
        .label Total Courses
      .column-80
        %span= student.courses.count
    .row
      .column-20
        .label Total Hours
      .column-80
        %span= student.courses.pluck(:number_of_lessons, :lesson_duration).inject(0) { |sum, data| sum + data[0] * data[1] / 60.0}
%br
%table.index_table
  %thead
    %tr
      %th.col ID
      %th.col Code
      %th.col Status
      %th.col Teachers
      %th.col Number of lessons
      %th.col Total hours
      %th.col Lesson length
      %th.col Price
  %tbody
    - student.courses.each.with_index do |course, index|
      %tr{ class: "#{index % 2 == 0 ? 'odd' : 'even'}" }
        %td.col
          %a{ href: "#{course_path(course)}" }= course.id
        %td.col
          %a{ href: "#{course_path(course)}" }= course.code
        %td.col
          %span.status_tag{ class: admin_statuses[course.status] }= course.status
        %td.col
          - course.teachers.each.with_index do |teacher, index|
            - if index > 0
              %span,
            %a{ href: "#{user_path(teacher)}" }= teacher.full_name
        %td.col= "#{course.number_of_learned_lessons} / #{course.number_of_lessons}"
        %td.col= "#{course.learned_lessons.to_a.sum { |ls| ls.length } / 60} / #{course.number_of_lessons * course.lesson_duration / 60}"
        %td.col= course.lesson_duration
        %td.col= money_format course.price

app/views/admin/dashboard/student/_statistics.haml
%br
#statistic
  .header Statistic
  .body
    .row
      .column-20
        .label Total students
      .column-80
        %span= students.count
    .row
      .column-20
        .label Total courses
      .column-80
        %span= students.inject(0) { |sum, s| sum + s[1].pluck(:course_id).uniq.count }
%br
%br
%table.index_table
  %thead
    %tr
      %th.col ID
      %th.col Student
      %th.col Total courses
      %th.col Total lessons
      %th.col Total hours
      %th.col Total teachers
      %th.col Total payments
      %th.col Actions
  %tbody
    - students.each.with_index do |data, index|
      - student, lesson_schedules = data
      %tr{ class: "#{index % 2 == 0 ? 'odd' : 'even'}" }
        %td.col
          %a{ href: "#{user_path(student)}" }= student.id
        %td.col
          %a{ href: "#{user_path(student)}" }= student.full_name
        %td.col= lesson_schedules.pluck(:course_id).uniq.count
        %td.col= lesson_schedules.count
        %td.col= lesson_schedules.inject(0) { |acc, elem| acc + elem.length / 60.0 }
        %td.col
          - Teacher.where(id: lesson_schedules.pluck(:teacher_id).uniq).each.with_index do |teacher, index|
            - if index > 0
              %span,
            %a{ href: "#{user_path(teacher)}" }= teacher.full_name
        %td.col= money_format lesson_schedules.inject(Money.new(0)) { |acc, elem| acc + elem.price }
        %td.col
          %a{ href: "#{dashboard_student_path(student_id: student.id)}" } View