config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  post '/paper_trail_versions/:id/revert', to: 'paper_trail_versions#revert', as: :revert_paper_trail_version

  resources :charts do
    collection do
      get :student_fees
    end
  end

  resources :graphql, only: [:index, :create]

  mount GraphiQL::Rails::Engine, at: "/graphiql", graphql_path: "/graphql"

  mount Client::Route => '/client'
  mount Partner::Route => '/agency'
end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  extend FriendlyId

  enum role: [:superadmin, :admin, :manager, :editor]

  devise :database_authenticatable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :creating_users, class_name: User, foreign_key: :creator_id

  friendly_id :slug_candidates, use: [:slugged, :finders]

  def admin?
    super || superadmin?
  end

  def manager?
    super || superadmin?
  end

  def editor?
    super || admin?
  end

  private

  def slug_candidates
    [
      :full_name,
      [:id, :full_name],
      [:email]
    ]
  end
end

app/models/course.rb
class Course < ActiveRecord::Base
  include UniqueCode

  enum status: [:in_process, :completed, :cancel]

  monetize :price_units
  has_paper_trail on: [:create, :update, :destroy]

  belongs_to :student, class_name: Student
  belongs_to :creator, class_name: AdminUser, foreign_key: :creator_id
  has_many :course_schedules, dependent: :destroy
  has_many :lesson_schedules, dependent: :destroy
  has_many :course_notes, dependent: :destroy
  has_many :comments, as: :commentable, dependent: :destroy
  has_many :course_comments, class_name: Comment, as: :commentable, dependent: :destroy

  has_many :course_teachers, dependent: :destroy
  has_many :teachers, through: :course_teachers

  has_one :active_course_teacher, -> { active }, class_name: CourseTeacher, foreign_key: :course_id
  has_one :active_teacher, through: :active_course_teacher, source: :teacher

  validates :lesson_duration, :number_of_reschedule, :started_date, :time_zone, presence: true
  validate :overlap_teaching_schedules?, on: :create
  validate :avaiable_lesson_packages?, on: :create
  validate :overlap_weekly_schedules?, on: :create

  scope :order_by_id, -> { order(id: :desc) }
  scope :will_be_swapped, -> (length = 20) do
    join_sql = <<-SQL
      INNER JOIN (
        SELECT courses.id
        FROM courses
          INNER JOIN course_teachers ON courses.id = course_teachers.course_id
          INNER JOIN lesson_schedules ON courses.id = lesson_schedules.course_id
        WHERE
          courses.status = #{Course.statuses[:in_process]}
          AND courses.number_of_lessons > #{length}
          AND course_teachers.status = #{CourseTeacher.statuses[:active]}
          AND lesson_schedules.teacher_id = course_teachers.teacher_id
          AND lesson_schedules.started_time <= CURRENT_TIMESTAMP
          AND lesson_schedules.status IN (#{[:official, :insert].map { |s| LessonSchedule.statuses[s] }.join(',')})
        GROUP BY courses.id
        HAVING count(courses.id) >= 20
      ) as swapped_courses ON courses.id = swapped_courses.id
    SQL
    joins(join_sql)
  end

  accepts_nested_attributes_for :course_schedules, allow_destroy: true
  accepts_nested_attributes_for :course_teachers, allow_destroy: true

  def remain_of_lessons
    number_of_lessons - number_of_learned_lessons
  end

  def learned_lessons
    lesson_schedules.be_learned.where('ended_time <= ?', Time.current)
  end

  def number_of_learned_lessons
    learned_lessons.count
  end

  private

  def overlap_weekly_schedules?
    teacher = course_teachers.find { |ct| ct.active? }.teacher
    in_weekly = course_schedules.all? do |cs|
      teacher.weekly_schedules.exists? [
        'block_range @> int4range(?, ?) OR block_range @> int4range(?, ?)',
        cs.block_range_begin, cs.block_range_end,
        cs.block_range_begin + 336, cs.block_range_end + 336
      ]
    end

    if !in_weekly
      errors.add(:base, "Not available in #{teacher.full_name}'s weekly schedules")
    end
  end

  def overlap_teaching_schedules?
    teacher = course_teachers.find { |ct| ct.active? }.teacher
    in_teaching = Generator::LessonSchedulesService.new(self).course_date_ranges.any? do |rdate|
      teacher.lesson_schedules.be_learned.exists? [
        '(started_time >= :started_time AND started_time < :ended_time) OR (ended_time > :started_time AND ended_time <= :ended_time)',
        { started_time: rdate.first, ended_time: rdate.last }
      ]
    end

    if in_teaching
      errors.add(:base, "Overlap in teaching schedules")
    end
  end

  def avaiable_lesson_packages?
    if student.wallet.price < price
      errors.add(:base, 'User does not have enough money for this course')
    end
  end
end

app/views/admin/admin_users/_edit.html.erb
<% context.instance_eval do
  f.inputs "Admin Details" do
    f.input :role, as: :string, input_html: { disabled: true, value: f.object.role.titleize }
    f.input :email
    f.input :full_name
  end
  render 'admin/admin_users/teachers', f: f, resource: resource
end %>

app/views/admin/admin_users/_new.html.erb
<% context.instance_eval do
  f.inputs "Admin Details" do
    f.input :email
    f.input :full_name
    f.input :password
    f.input :password_confirmation
    f.input :role, as: :select, collection: admin_role_opts, include_blank: false, selected: f.object.role || 'admin'
  end
end %>

app/views/admin/admin_users/_teacher.html.haml
%fieldset.inputs.has_many_fields
  %ol
    - g.input :teacher, label: 'Teacher', as: :select, collection: Teacher.all, input_html: { name: 'admin_user[teacher_ids][]', value: teacher_id }, selected: teacher_id
    %li
      %a.button.has_many_remove{ href: '#' } Remove

app/views/admin/admin_users/_teachers.html.haml
- f.inputs 'List of teachers' do
  - f.fields_for :teacher_ids do |g|
    %li.has_many_container
      - resource.teacher_ids.each do |teacher_id|
        = render 'admin/admin_users/teacher', teacher_id: teacher_id, g: g
      - template = render('admin/admin_users/teacher', teacher_id: nil, g: g)
      %a.button.has_many_add{ href: '#', data: { html: template.html_safe, placeholder: 'NEW_TEACHER' } } New Teacher